### ISSUE TITLE
Calendar doesn't work in horizontal on phone

### ISSUE THREAD

**Issue by Computerkrack** [Dlurak/dloolFrontend#12]
PWA on iPhone 11
![image](https://github.com/Dlurak/dloolFrontend/assets/93448496/2004e2b3-0136-498e-9d4e-eccfdf10de6d)

**Comment by Dlurak** [comment]
Thanks for the feedback!
I've investigated that issue and here is what i found so far:
- The issue happens when the screen is big enough to get the two column layout
- The div with all of the content has a height of 0 if the height of the navigation + footer isn't bigger than the screen. A smartphone screen is very narrow, so in landscape it is big enough to show everything.

**Comment by Dlurak** [comment]
I will probably change the height once more in the near future, it looks good on small screens but now it is very small on big screens.
